import Image from "next/image";
import Link from "next/link";
import { PageHero } from "@/components/PageHero";
import { company } from "@/data/company";
import { createPageMetadata } from "@/data/site";

export const metadata = createPageMetadata({ title: "About MULIFANG INC.", description: "Learn about MULIFANG INC., a premium custom furniture manufacturer based in Bamban, Tarlac, Philippines.", path: "/about" });
const values = [["Precision", "We coordinate dimensions, details and production stages with care."], ["Accountability", "One connected team guides each approved project through completion."], ["Practical Design", "Furniture should be refined, durable and genuinely useful every day."], ["Material Respect", "Finishes and components are selected in line with the project purpose."], ["Clear Communication", "Clients receive a defined process from consultation to installation."], ["Long-Term Thinking", "We build relationships and furniture solutions intended to last."]];

export default function AboutPage() { return <>
  <PageHero eyebrow="About MULIFANG" title="Designed for living. Built for life." text="A premium custom furniture manufacturer connecting design coordination, engineering, CNC manufacturing, delivery and professional installation." />
  <section className="content-section"><div className="container split"><div><p className="eyebrow">Company Profile</p><h2>Based in Tarlac. Built to serve growing projects.</h2></div><div className="intro-copy"><p>MULIFANG INC. is a premium custom furniture manufacturer based in Bamban, Tarlac, Philippines.</p><p>The company provides complete furniture solutions for residential, apartment, hotel, office and commercial projects. Services include consultation, design coordination, engineering, CNC manufacturing, delivery and professional installation.</p><p>Established in {company.established}, MULIFANG is developing a capable local team and an efficient production base for custom and coordinated project work.</p></div></div></section>
  <section className="content-section alt"><div className="container factory-layout"><div><p className="eyebrow">Brand Position</p><h2>Premium Custom Furniture Manufacturer</h2><p className="lead" style={{marginTop:28}}>Architectural furniture solutions shaped around real spaces and delivered through an accountable process.</p></div><div className="image-wrap" style={{aspectRatio:"16/10"}}><Image src="/images/projects/living-project.webp" alt="MULIFANG custom living room furniture concept" fill sizes="60vw" /></div></div></section>
  <section className="content-section"><div className="container"><div className="section-heading"><div><p className="eyebrow">Direction</p><h2>What guides our work.</h2></div></div><div className="values-grid"><div className="value-card"><h3>Mission</h3><p>To provide coordinated custom furniture solutions that combine practical design, precise production and dependable project service.</p></div><div className="value-card"><h3>Vision</h3><p>To become a trusted Philippine furniture manufacturing partner for complete residential, hospitality, office and commercial interiors.</p></div><div className="value-card"><h3>Service Promise</h3><p>To communicate clearly, manufacture responsibly and support every approved project through delivery and installation.</p></div></div></div></section>
  <section className="content-section alt"><div className="container"><div className="section-heading"><div><p className="eyebrow">Core Values</p><h2>How we work.</h2></div></div><div className="values-grid">{values.map(([title,text]) => <div className="value-card" key={title}><h3>{title}</h3><p>{text}</p></div>)}</div></div></section>
  <section className="service-area"><div className="container"><p className="eyebrow light">Service Areas</p><h2>{company.areas.join(" · ")}</h2><p>Consultation, measurement, delivery and installation are scheduled according to project scope and location.</p></div></section>
  <section className="quote-banner"><div className="container"><p className="eyebrow">Work With MULIFANG</p><h2>Plan your next interior with us.</h2><p>Tell us about your property, product needs and preferred schedule.</p><Link className="button button-dark" href="/contact#quotation">Contact Our Team</Link></div></section>
  </>; }
