import Image from "next/image";
import Link from "next/link";
import { company } from "@/data/company";
import { messages } from "@/i18n/messages";
import { route, type Locale } from "@/i18n/config";

export function LaunchExtras({locale}:{locale:Locale}) {
  const sets = {
    en: { eye:"Collection Logic", title:"Made to sell clearly—and build efficiently.", items:[["Small-space utility","Multifunctional furniture and efficient footprints answer the realities of Philippine homes."],["Visible storage value","Drawers, cubbies and concealed compartments make benefits immediately understandable."],["Repeatable production","Shared board thicknesses and common hardware reduce part variety and speed assembly."],["Social-commerce ready","Clear names, exact product codes and accessible prices support online presentation."]] },
    zh: { eye:"系列逻辑", title:"产品易于理解，生产更高效。", items:[["小空间实用性","多功能家具与高效占地适应菲律宾住宅的真实需求。"],["清晰的收纳价值","抽屉、格位与隐藏空间让功能一目了然。"],["可重复生产","统一板厚与通用五金减少零件种类并提升装配效率。"],["适合线上销售","清晰名称、准确产品代码与易理解价格支持线上展示。"]] },
    ko: { eye:"컬렉션 원칙", title:"명확한 판매와 효율적인 생산을 위해.", items:[["소형 공간 활용","다기능 가구와 효율적인 수납이 필리핀 주거 환경에 대응합니다."],["분명한 수납 가치","서랍, 수납칸과 숨은 수납이 기능을 명확히 보여줍니다."],["반복 생산","통일된 보드 두께와 공용 하드웨어로 부품 종류와 조립 시간을 줄입니다."],["온라인 판매 최적화","명확한 이름, 정확한 제품 코드와 이해하기 쉬운 가격으로 온라인 소개를 지원합니다."]] },
  } as const;
  const x=sets[locale];
  return <section className="dark-section section"><div className="container"><div className="section-heading"><div><p className="eyebrow light">{x.eye}</p><h2>{x.title}</h2></div></div><div className="principles-grid">{x.items.map(([a,b],i)=><article key={a}><span>0{i+1}</span><h3>{a}</h3><p>{b}</p></article>)}</div></div></section>;
}

export function ProjectExtras({locale}:{locale:Locale}){const m=messages[locale];const x=locale==="en"?{approach:"Project Approach",approachTitle:"One accountable process.",steps:["Consultation","Site Measurement","Concept Design","Material Selection","Quotation","Engineering Drawings","CNC Manufacturing","Quality Inspection","Delivery","Installation","Project Handover"],interior:"Interior Design Capability",interiorTitle:"Furniture, cabinetry and room planning in one system.",cards:[["kitchen-project","Kitchen & Pantry Systems","Coordinated cabinetry, work zones and finishes planned around everyday use."],["hallway-project","Entry & Hallway Cabinetry","Purpose-built storage keeps arrival spaces calm and functional."],["wardrobe-project","Wardrobe & Storage Planning","Integrated storage tailored to the room and daily routine."]],enquiry:"Project Enquiry",title:"Bring us your plans.",text:"Share drawings, dimensions, reference images or a simple description."}:locale==="zh"?{approach:"项目方法",approachTitle:"一套全程负责的流程。",steps:["需求沟通","现场测量","概念设计","材料选择","报价","工程图纸","CNC 制造","质量检验","配送","安装","项目交付"],interior:"室内设计能力",interiorTitle:"家具、柜体与空间规划统一协同。",cards:[["kitchen-project","厨房与餐具室系统","围绕日常使用协调柜体、工作区与饰面。"],["hallway-project","玄关与走廊柜体","定制收纳让入口空间整洁、实用且舒适。"],["wardrobe-project","衣柜与收纳规划","根据房间、物品与日常习惯规划一体化收纳。"]],enquiry:"项目咨询",title:"把您的图纸交给我们。",text:"分享图纸、尺寸、参考图片或简单说明。"}:{approach:"프로젝트 방식",approachTitle:"하나의 책임 있는 프로세스.",steps:["상담","현장 실측","콘셉트 디자인","소재 선택","견적","엔지니어링 도면","CNC 제조","품질 검사","배송","설치","프로젝트 인도"],interior:"인테리어 디자인 역량",interiorTitle:"가구, 캐비닛과 공간 계획을 하나의 시스템으로.",cards:[["kitchen-project","주방 및 팬트리 시스템","일상 사용에 맞춘 캐비닛, 작업 구역과 마감을 통합합니다."],["hallway-project","현관 및 복도 캐비닛","맞춤 수납으로 입구 공간을 정돈하고 실용적으로 만듭니다."],["wardrobe-project","옷장 및 수납 계획","공간과 일상 습관에 맞춘 통합 수납을 계획합니다."]],enquiry:"프로젝트 문의",title:"도면을 공유해 주세요.",text:"도면, 치수, 참고 이미지 또는 간단한 설명을 보내 주세요."};return <><section className="content-section alt project-approach"><div className="container"><div className="section-heading"><div><p className="eyebrow">{x.approach}</p><h2>{x.approachTitle}</h2></div></div><ol className="workflow">{x.steps.map(s=><li key={s}><strong>{s}</strong></li>)}</ol></div></section><section className="content-section interior-section"><div className="container"><div className="section-heading"><div><p className="eyebrow">{x.interior}</p><h2>{x.interiorTitle}</h2></div></div><div className="interior-project-grid">{x.cards.map(([img,a,b])=><article className="interior-project-card" key={a}><div className="image-wrap"><Image src={`/images/projects/${img}.webp`} alt={a} fill sizes="33vw"/></div><h3>{a}</h3><p>{b}</p></article>)}</div></div></section><section className="quote-banner"><div className="container"><p className="eyebrow">{x.enquiry}</p><h2>{x.title}</h2><p>{x.text}</p><Link className="button button-dark" href={`${route(locale,"/contact")}#quotation`}>{m.quote}</Link></div></section></>}

export function FactoryExtras({locale}:{locale:Locale}){const x=locale==="en"?{items:["CNC cutting","Edge banding","Drilling","Machining","Assembly","Quality inspection","Dust collection","Packaging","Delivery coordination","Custom production","Batch production","Installation coordination"],labels:["Factory area","Major machines","Current employees","Planned workforce"]}:locale==="zh"?{items:["CNC 开料","封边","钻孔","机械加工","组装","质量检验","除尘","包装","配送协调","定制生产","批量生产","安装协调"],labels:["工厂面积","主要设备","现有员工","规划员工"]}:{items:["CNC 절단","엣지 밴딩","드릴링","가공","조립","품질 검사","집진","포장","배송 조율","맞춤 생산","대량 생산","설치 조율"],labels:["공장 면적","주요 설비","현재 직원","계획 인력"]};const stats=[[company.factoryArea,x.labels[0]],[company.machines,x.labels[1]],[company.employees,x.labels[2]],[company.plannedWorkforce,x.labels[3]]];return <><section className="content-section alt"><div className="container"><ul className="capability-list">{x.items.map(a=><li key={a}>{a}</li>)}</ul></div></section><section className="stats-band"><div className="container stats-grid">{stats.map(([a,b])=><div key={b}><strong>{a}</strong><span>{b}</span></div>)}</div></section></>}

export function AboutExtras({locale}:{locale:Locale}){const m=messages[locale];const x=locale==="en"?{brand:"Brand Position",position:"Premium Custom Furniture Manufacturer",cards:[["Mission","To provide coordinated custom furniture solutions combining practical design, precise production and dependable service."],["Vision","To become a trusted Philippine manufacturing partner for complete residential and commercial interiors."],["Service Promise","To communicate clearly and support every approved project through delivery and installation."]],areas:"Service Areas",areaText:"Consultation, measurement, delivery and installation are scheduled according to project scope and location.",work:"Work With MULIFANG",title:"Plan your next interior with us.",text:"Tell us about your property, product needs and preferred schedule."}:locale==="zh"?{brand:"品牌定位",position:"高端定制家具制造商",cards:[["使命","以实用设计、精准生产与可靠服务提供协同的定制家具解决方案。"],["愿景","成为菲律宾住宅与商业完整室内项目值得信赖的家具制造伙伴。"],["服务承诺","清晰沟通，并为获批项目提供从交付到安装的支持。"]],areas:"服务区域",areaText:"咨询、测量、配送与安装将根据项目范围和地点安排。",work:"与 MULIFANG 合作",title:"与我们规划您的下一个室内项目。",text:"请告诉我们物业情况、产品需求与期望时间。"}:{brand:"브랜드 포지션",position:"프리미엄 맞춤 가구 제조업체",cards:[["미션","실용적 디자인, 정밀한 생산과 신뢰할 수 있는 서비스로 통합 맞춤 가구 솔루션을 제공합니다."],["비전","필리핀의 주거 및 상업 인테리어를 위한 신뢰받는 가구 제조 파트너가 됩니다."],["서비스 약속","명확히 소통하고 승인된 프로젝트의 배송과 설치까지 지원합니다."]],areas:"서비스 지역",areaText:"상담, 실측, 배송 및 설치는 프로젝트 범위와 위치에 따라 일정이 조율됩니다.",work:"MULIFANG과 함께",title:"다음 인테리어 프로젝트를 계획하세요.",text:"공간, 제품 요구사항과 희망 일정을 알려주세요."};return <><section className="content-section alt"><div className="container factory-layout"><div><p className="eyebrow">{x.brand}</p><h2>{x.position}</h2></div><div className="image-wrap" style={{aspectRatio:"16/10"}}><Image src="/images/projects/living-project.webp" alt={x.position} fill sizes="60vw"/></div></div></section><section className="content-section"><div className="container values-grid">{x.cards.map(([a,b])=><div className="value-card" key={a}><h3>{a}</h3><p>{b}</p></div>)}</div></section><section className="service-area"><div className="container"><p className="eyebrow light">{x.areas}</p><h2>{company.areas.join(" · ")}</h2><p>{x.areaText}</p></div></section><section className="quote-banner"><div className="container"><p className="eyebrow">{x.work}</p><h2>{x.title}</h2><p>{x.text}</p><Link className="button button-dark" href={`${route(locale,"/contact")}#quotation`}>{m.quote}</Link></div></section></>}
