"use client";

import { useState } from "react";
import type { FormEvent, MouseEvent } from "react";
import { company } from "@/data/company";
import { products } from "@/data/products";
import { messages } from "@/i18n/messages";
import { localizeProduct } from "@/i18n/products";
import type { Locale } from "@/i18n/config";

type QuoteData=Record<string,string>;
const base:QuoteData={fullName:"",phone:"",email:"",location:"",customerType:"homeowner",productCategory:"",productName:"",productCode:"",priceReference:"",quantity:"1",dimensions:"",material:"",color:"",budget:"undecided",deliveryDate:"",installation:"yes",details:""};
const labelSets={
  en:{fullName:"Full Name",phone:"Phone / WhatsApp",email:"Email",location:"City / Province",customerType:"Customer Type",productCategory:"Product Category",productName:"Product Name",productCode:"Product Code",priceReference:"Reference Price",quantity:"Quantity",dimensions:"Dimensions",material:"Preferred Material",color:"Preferred Color",budget:"Budget Range",deliveryDate:"Target Delivery Date",installation:"Installation Required",details:"Project Details"},
  zh:{fullName:"姓名",phone:"电话 / WhatsApp",email:"电子邮箱",location:"城市 / 省份",customerType:"客户类型",productCategory:"产品类别",productName:"产品名称",productCode:"产品代码",priceReference:"参考价格",quantity:"数量",dimensions:"尺寸",material:"首选材料",color:"首选颜色",budget:"预算范围",deliveryDate:"期望交付日期",installation:"是否需要安装",details:"项目详情"},
  ko:{fullName:"성명",phone:"전화 / WhatsApp",email:"이메일",location:"도시 / 주",customerType:"고객 유형",productCategory:"제품 카테고리",productName:"제품명",productCode:"제품 코드",priceReference:"참고 가격",quantity:"수량",dimensions:"치수",material:"선호 소재",color:"선호 색상",budget:"예산 범위",deliveryDate:"희망 배송일",installation:"설치 필요 여부",details:"프로젝트 상세"}
} as const;
const optionSets={
  en:{customer:[["homeowner","Homeowner"],["designer","Interior Designer"],["architect","Architect"],["contractor","Contractor"],["developer","Property Developer"],["business","Business / Organization"],["other","Other"]],budget:[["undecided","Not decided"],["below100","Below PHP 100,000"],["100-300","PHP 100,000–300,000"],["300-600","PHP 300,000–600,000"],["600-1000","PHP 600,000–1,000,000"],["above1000","Above PHP 1,000,000"]],install:[["yes","Yes"],["no","No"],["discuss","To be discussed"]]},
  zh:{customer:[["homeowner","业主"],["designer","室内设计师"],["architect","建筑师"],["contractor","承包商"],["developer","房地产开发商"],["business","企业 / 机构"],["other","其他"]],budget:[["undecided","尚未确定"],["below100","低于 PHP 100,000"],["100-300","PHP 100,000–300,000"],["300-600","PHP 300,000–600,000"],["600-1000","PHP 600,000–1,000,000"],["above1000","高于 PHP 1,000,000"]],install:[["yes","需要"],["no","不需要"],["discuss","待商议"]]},
  ko:{customer:[["homeowner","주택 소유자"],["designer","인테리어 디자이너"],["architect","건축가"],["contractor","시공사"],["developer","부동산 개발사"],["business","기업 / 기관"],["other","기타"]],budget:[["undecided","미정"],["below100","PHP 100,000 미만"],["100-300","PHP 100,000–300,000"],["300-600","PHP 300,000–600,000"],["600-1000","PHP 600,000–1,000,000"],["above1000","PHP 1,000,000 초과"]],install:[["yes","예"],["no","아니요"],["discuss","협의 필요"]]}
} as const;

type Props={locale:Locale;initialProduct?:string;initialCode?:string;initialPrice?:string;initialQuantity?:string};
export function QuoteForm({locale,initialProduct="",initialCode="",initialPrice="",initialQuantity="1"}:Props){
  const m=messages[locale], labels=labelSets[locale], options=optionSets[locale];
  const matched=products.find(p=>p.code===initialCode||p.name===initialProduct); const lp=matched?localizeProduct(matched,locale):undefined;
  const [data,setData]=useState<QuoteData>({...base,productName:initialProduct||lp?.localizedName||"",productCode:initialCode,priceReference:initialPrice,quantity:initialQuantity||"1",productCategory:lp?.localizedCategory||""});
  const [summary,setSummary]=useState(""),[message,setMessage]=useState(""); const update=(n:string,v:string)=>setData(c=>({...c,[n]:v}));
  const optionLabel=(group:readonly (readonly string[])[],value:string)=>group.find(x=>x[0]===value)?.[1]||value;
  const build=()=>`${m.quoteForm.requestTitle}\n${"-".repeat(30)}\n${Object.entries(labels).map(([key,label])=>`${label}: ${key==="customerType"?optionLabel(options.customer,data[key]):key==="budget"?optionLabel(options.budget,data[key]):key==="installation"?optionLabel(options.install,data[key]):data[key]||m.quoteForm.unspecified}`).join("\n")}\n\n${m.price.reference}\n\n${m.quoteForm.submitted}`;
  const validate=()=>{if(!data.fullName||!data.phone||!data.email||!data.location||!data.details){setMessage(m.quoteForm.required);return false;}return true;};
  const generate=(e?:FormEvent)=>{e?.preventDefault();if(!validate())return;setSummary(build());setMessage(m.quoteForm.ready);}; const share=summary||build();
  const prepare=(e:MouseEvent<HTMLAnchorElement>)=>{if(!validate()){e.preventDefault();return;}setSummary(share);setMessage(m.quoteForm.sendReady);};
  const copy=async()=>{if(!validate())return;const text=summary||build();setSummary(text);await navigator.clipboard.writeText(text);setMessage(m.quoteForm.copied);};
  const categories=[...new Set(products.map(p=>localizeProduct(p,locale).localizedCategory))];
  const field=(name:keyof typeof labels,opts?:{type?:string;options?:readonly (readonly string[])[]|string[];full?:boolean;required?:boolean;placeholder?:string;readOnly?:boolean})=><div className={`field ${opts?.full?"full":""}`} key={name}><label htmlFor={name}>{labels[name]}{opts?.required?" *":""}</label>{name==="details"?<textarea id={name} value={data[name]} onChange={e=>update(name,e.target.value)} placeholder={opts?.placeholder} required/>:opts?.options?<select id={name} value={data[name]} onChange={e=>update(name,e.target.value)}>{opts.options.map(o=>typeof o==="string"?<option key={o}>{o}</option>:<option key={o[0]} value={o[0]}>{o[1]}</option>)}</select>:<input id={name} type={opts?.type||"text"} value={data[name]} onChange={e=>update(name,e.target.value)} placeholder={opts?.placeholder} required={opts?.required} min={opts?.type==="number"?"1":undefined} readOnly={opts?.readOnly}/>}</div>;
  const placeholders=locale==="en"?["Specific product or room","e.g. MF-LR-TV1800","Suggested retail price or quotation basis","Width × height × depth, or room size","e.g. oak veneer, laminate","Preferred tone or finish","Describe the space, scope, style direction and any site considerations."]:locale==="zh"?["具体产品或房间","例如 MF-LR-TV1800","建议零售价或报价依据","宽 × 高 × 深，或房间尺寸","例如橡木木皮、饰面板","首选色调或饰面","请描述空间、范围、风格方向及现场情况。"]:["특정 제품 또는 공간","예: MF-LR-TV1800","권장 소비자가 또는 견적 기준","가로 × 높이 × 깊이 또는 공간 크기","예: 오크 무늬목, 라미네이트","선호 색상 또는 마감","공간, 범위, 스타일 방향 및 현장 조건을 설명해 주세요."];
  return <form className="quote-form" onSubmit={generate} noValidate><p className="eyebrow">{m.quoteForm.eyebrow}</p><h2>{m.quoteForm.title}</h2><p className="quote-form-intro">{m.quoteForm.intro}</p><p className="quotation-reference-note">{m.price.reference}</p><div className="form-grid">{field("fullName",{required:true})}{field("phone",{type:"tel",required:true})}{field("email",{type:"email",required:true})}{field("location",{required:true})}{field("customerType",{options:options.customer})}{field("productCategory",{options:categories})}{field("productName",{placeholder:placeholders[0]})}{field("productCode",{placeholder:placeholders[1]})}{field("priceReference",{placeholder:placeholders[2]})}{field("quantity",{type:"number"})}{field("dimensions",{placeholder:placeholders[3]})}{field("material",{placeholder:placeholders[4]})}{field("color",{placeholder:placeholders[5]})}{field("budget",{options:options.budget})}{field("deliveryDate",{type:"date"})}{field("installation",{options:options.install})}{field("details",{full:true,required:true,placeholder:placeholders[6]})}</div><div className="form-actions"><button className="button button-dark" type="button" onClick={() => generate()}>{m.quoteForm.generate}</button><a className="button secondary" href={`https://wa.me/${company.whatsapp}?text=${encodeURIComponent(share)}`} target="_blank" rel="noreferrer" onClick={prepare}>{m.quoteForm.sendWhatsApp}</a><a className="button secondary" href={`mailto:${company.email}?subject=${encodeURIComponent(m.quoteForm.requestTitle)}&body=${encodeURIComponent(share)}`} onClick={prepare}>{m.quoteForm.sendEmail}</a><button className="button secondary" type="button" onClick={copy}>{m.quoteForm.copy}</button></div>{message&&<p className="form-message" role="status">{message}</p>}{summary&&<div className="summary-box" aria-label={m.quoteForm.summary}>{summary}</div>}</form>;
}
