import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { PageHero } from "@/components/PageHero";
import { LocalizedProductPrice } from "@/components/LocalizedProductPrice";
import { company } from "@/data/company";
import { formatProductPrice } from "@/data/products";
import { absoluteUrl } from "@/data/site";
import { route, type Locale } from "@/i18n/config";
import { messages } from "@/i18n/messages";
import { localizedProduct, localizedProducts } from "@/i18n/products";

const pick = <T,>(locale: Locale, values: Record<Locale, T>) => values[locale];

export function RestoredProductPage({ locale, slug }: { locale: Locale; slug: string }) {
  const m = messages[locale];
  const item = localizedProduct(slug, locale);
  if (!item) notFound();
  const related = localizedProducts(locale).filter(product => product.system === item.system && product.category === item.category && product.slug !== item.slug).slice(0, 3);
  const price = formatProductPrice(item);
  const quote = `${route(locale, "/contact")}?product=${encodeURIComponent(item.localizedName)}&code=${item.code}&price=${encodeURIComponent(price)}&quantity=1#quotation`;
  const productNumber = pick(locale, { en: "Product number", zh: "产品编号", ko: "제품 번호" });
  const whatsapp = `${m.quote}: ${item.localizedName} (${item.code}). ${m.common.code}: ${price}. ${m.price.reference}`;
  const schema = { "@context": "https://schema.org", "@type": "Product", sku: item.code, name: item.localizedName, category: item.localizedCategory, description: item.localizedDescription, image: item.gallery.map(absoluteUrl), brand: { "@type": "Brand", name: "MULIFANG" }, offers: item.suggestedRetailPrice !== null ? { "@type": "Offer", priceCurrency: item.currency, price: item.suggestedRetailPrice, availability: "https://schema.org/InStock", url: absoluteUrl(route(locale, `/products/${item.slug}`)), description: m.price.reference } : { "@type": "Offer", priceSpecification: { "@type": "PriceSpecification", description: m.price.upon }, availability: "https://schema.org/InStock" } };

  return <>
    <section className="product-hero">
      <div className="product-hero-image"><Image src={item.mainImage} alt={item.localizedName} fill priority sizes="(max-width:760px) 100vw, 56vw" /></div>
      <div className="product-hero-copy"><p className="eyebrow">{item.system === "launch" ? m.common.collection : m.common.customSolutions} · {item.localizedCategory}</p><p className="product-code">{item.code}</p><h1>{item.localizedName}</h1><p className="lead">{item.localizedDescription}</p><LocalizedProductPrice product={item} locale={locale} /><div className="button-row"><Link className="button button-dark" href={quote}>{m.quote}</Link><a className="button secondary-dark" href={`https://wa.me/${company.whatsapp}?text=${encodeURIComponent(whatsapp)}`} target="_blank" rel="noreferrer">WhatsApp</a></div></div>
    </section>
    {item.system === "launch" ? <>
      <section className="content-section"><div className="container product-specs"><div className="spec-card"><span>{productNumber}</span><strong>{String(item.number).padStart(2, "0")} / 20</strong></div><div className="spec-card"><span>{m.common.dimensions}</span><strong>{item.localizedDimensions}</strong></div><div className="spec-card"><span>{m.common.packaging}</span><strong>{item.localizedPackaging}</strong></div><div className="spec-card"><span>{m.common.status}</span><strong>{m.common.active}</strong></div></div><div className="container detail-grid launch-details"><div><div className="detail-block"><h2>{m.common.details}</h2><ul>{item.localizedFeatures.map(value => <li key={value}>{value}</li>)}</ul></div><div className="detail-block"><h2>{m.common.materials}</h2><ul>{item.localizedMaterials.map(value => <li key={value}>{value}</li>)}</ul></div></div><div><div className="detail-block"><h2>{m.common.customers}</h2><ul>{item.localizedCustomers.map(value => <li key={value}>{value}</li>)}</ul></div><div className="detail-block"><h2>{m.common.positioning}</h2><p>{item.localizedShortDescription}</p></div></div></div></section>
      {item.gallery.length > 1 && <section className="content-section product-gallery-section"><div className="container"><div className="section-heading"><div><p className="eyebrow">{m.common.gallery}</p><h2>{m.common.additional}</h2></div><p>{m.common.galleryNote}</p></div><div className="product-gallery-grid">{item.gallery.slice(1).map((image, index) => <div className="image-wrap" key={image}><Image src={image} alt={`${item.localizedName} ${m.common.additional} ${index + 1}`} fill sizes="(max-width:760px) 100vw, 70vw" /></div>)}</div></div></section>}
      <section className="content-section alt"><div className="container exploded-layout"><div><p className="eyebrow">{m.common.construction}</p><h2>{m.common.exploded}</h2><p>{m.common.explodedNote}</p></div><div className="exploded-image image-wrap"><Image src={item.explodedViewImage} alt={`${item.localizedName} ${m.common.exploded}`} fill sizes="(max-width:760px) 100vw, 60vw" /></div></div></section>
      <section className="pricing-note"><div className="container"><p>{m.price.estimate}</p><p>{m.price.terms}</p><p>{m.price.reference}</p></div></section>
    </> : <section className="content-section"><div className="container detail-grid"><div><div className="detail-block"><h2>{m.common.details}</h2><ul>{item.localizedFeatures.map(value => <li key={value}>{value}</li>)}</ul></div><div className="detail-block"><h2>{m.common.materials}</h2><ul>{item.localizedMaterials.map(value => <li key={value}>{value}</li>)}</ul></div></div><div><div className="detail-block"><h2>{m.common.customization}</h2><ul>{item.localizedCustomization.map(value => <li key={value}>{value}</li>)}</ul></div><div className="detail-block"><h2>{m.common.applications}</h2><ul>{item.localizedApplications.map(value => <li key={value}>{value}</li>)}</ul></div></div></div></section>}
    <section className="section"><div className="container"><div className="section-heading"><div><p className="eyebrow">{m.common.related}</p><h2>{m.common.continue}</h2></div><Link className="text-link" href={route(locale, "/products")}>{m.common.allProducts} <span>↗</span></Link></div><div className="product-grid">{related.map(product => <article className={`product-card ${product.system}`} key={product.slug}><Link href={route(locale, `/products/${product.slug}`)}><div className="image-wrap"><Image src={product.mainImage} alt={product.localizedName} fill sizes="33vw" /></div><p className="category">{product.localizedCategory}</p><h2>{product.localizedName}</h2></Link><LocalizedProductPrice product={product} locale={locale} compact /></article>)}</div></div></section>
    <section className="quote-banner"><div className="container"><p className="eyebrow">{m.common.writtenQuote}</p><h2>{m.common.askAbout} {item.localizedName}.</h2><p>{m.common.requestHelp}</p><Link className="button button-dark" href={quote}>{m.quote}</Link></div></section>
    <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} />
  </>;
}

const launchCopy = {
  en: { title: "Designed for repeatable production and Philippine living.", lead: "Twenty standardized furniture products positioned between entry-level furniture and premium imported systems—supported by MULIFANG’s local manufacturing and project customization capability.", browse: "Browse All 20 Products", hero: "Hero Launch Products", five: "Five products lead the collection.", heroText: "NEST, LIFT, REST, FAMILY and FOCUS span living, bedroom, dining and home office needs.", complete: "Complete Range", all: "All 20 launch SKUs.", search: "Search and filter products", stats: ["Launch SKUs", "Room categories", "Suggested retail range", "Core board platform", "Primary production modules"], logic: "Collection Logic", logicTitle: "Made to sell clearly—and build efficiently.", principles: [["Small-space utility", "Multifunctional furniture, shallow storage and efficient footprints answer the realities of Philippine homes."], ["Visible storage value", "Drawers, cubbies, appliance niches and concealed compartments make benefits immediately understandable."], ["Repeatable production", "Shared board thicknesses, repeated drawer boxes and common hardware reduce part variety and speed assembly."], ["Social-commerce ready", "Clear names, strong silhouettes, exact product codes and accessible prices support online presentation."]], request: "Request a product quotation.", requestText: "Choose any product to send its exact name, code, reference price and quantity to the MULIFANG team.", choose: "Choose a Product" },
  zh: { title: "为可重复生产与菲律宾生活方式而设计。", lead: "20 款标准化家具产品，定位于入门家具与高端进口系统之间，并由 MULIFANG 本地制造与项目定制能力提供支持。", browse: "浏览全部 20 款产品", hero: "首发主推产品", five: "五款产品引领整个系列。", heroText: "NEST、LIFT、REST、FAMILY 与 FOCUS 覆盖客厅、卧室、餐厅及家庭办公需求。", complete: "完整系列", all: "全部 20 个首发产品。", search: "搜索和筛选产品", stats: ["首发产品", "空间类别", "建议零售价范围", "核心板材体系", "主要生产模块"], logic: "系列逻辑", logicTitle: "产品易于理解，生产更高效。", principles: [["小空间实用性", "多功能家具、浅型收纳与高效占地适应菲律宾住宅需求。"], ["清晰的收纳价值", "抽屉、格位、家电位与隐藏空间让功能一目了然。"], ["可重复生产", "统一板厚、重复抽屉结构与通用五金减少零件种类并提升装配效率。"], ["适合线上销售", "清晰名称、鲜明轮廓、准确代码与易理解价格支持线上展示。"]], request: "申请产品报价。", requestText: "选择任一产品，即可将准确名称、代码、参考价格及数量发送给 MULIFANG 团队。", choose: "选择产品" },
  ko: { title: "반복 생산과 필리핀 생활을 위해 설계했습니다.", lead: "20개의 표준화 가구 제품을 합리적인 가구와 프리미엄 수입 시스템 사이에 포지셔닝하고, MULIFANG의 현지 제조 및 맞춤 역량으로 지원합니다.", browse: "20개 제품 모두 보기", hero: "대표 출시 제품", five: "다섯 제품이 컬렉션을 이끕니다.", heroText: "NEST, LIFT, REST, FAMILY와 FOCUS는 거실, 침실, 다이닝 및 홈 오피스 요구를 아우릅니다.", complete: "전체 컬렉션", all: "20개 출시 제품 전체.", search: "제품 검색 및 필터", stats: ["출시 제품", "공간 카테고리", "권장 소비자가 범위", "핵심 보드 플랫폼", "주요 생산 모듈"], logic: "컬렉션 원칙", logicTitle: "명확한 판매와 효율적인 생산을 위해.", principles: [["소형 공간 활용", "다기능 가구, 얕은 수납과 효율적인 크기로 필리핀 주거 환경에 대응합니다."], ["분명한 수납 가치", "서랍, 수납칸, 가전 공간과 숨은 수납이 기능을 명확히 보여줍니다."], ["반복 생산", "통일된 보드 두께, 반복 서랍 구조와 공용 하드웨어로 부품과 조립 시간을 줄입니다."], ["온라인 판매 최적화", "명확한 이름, 형태, 제품 코드와 가격으로 온라인 소개를 지원합니다."]], request: "제품 견적을 요청하세요.", requestText: "제품을 선택하면 정확한 이름, 코드, 참고 가격과 수량을 MULIFANG 팀에 전달할 수 있습니다.", choose: "제품 선택" }
} as const;

export function RestoredLaunchPage({ locale }: { locale: Locale }) {
  const m = messages[locale], copy = launchCopy[locale], products = localizedProducts(locale).filter(product => product.system === "launch"), range = "₱2,490–₱24,990";
  const stats = [["20", copy.stats[0]], ["5", copy.stats[1]], [range, copy.stats[2]], ["18 mm", copy.stats[3]], ["4–6", copy.stats[4]]];
  return <>
    <section className="launch-page-hero"><div className="container"><p className="eyebrow light">{m.common.collection}</p><h1>{copy.title}</h1><p className="lead">{copy.lead}</p><div className="button-row"><Link className="button button-gold" href={route(locale, "/products")}>{copy.browse}</Link><Link className="text-link light-link" href={`${route(locale, "/contact")}#quotation`}>{m.quote} <span>↗</span></Link></div></div></section>
    <section className="collection-stats"><div className="container collection-stats-grid">{stats.map(([value, label]) => <div key={label}><strong>{value}</strong><span>{label}</span></div>)}</div></section>
    <section className="section"><div className="container section-heading"><div><p className="eyebrow">{copy.hero}</p><h2>{copy.five}</h2></div><p>{copy.heroText}</p></div><div className="container launch-hero-grid">{products.filter(product => product.featured).map(product => <article className="launch-hero-card" key={product.slug}><Link href={route(locale, `/products/${product.slug}`)}><div className="image-wrap"><Image src={product.mainImage} alt={product.localizedName} fill sizes="(max-width:760px) 100vw, 33vw" /></div><p>{product.code} · {product.localizedCategory}</p><h3>{product.localizedName}</h3></Link><LocalizedProductPrice product={product} locale={locale} compact /></article>)}</div></section>
    <section className="dark-section section"><div className="container"><div className="section-heading"><div><p className="eyebrow light">{copy.logic}</p><h2>{copy.logicTitle}</h2></div></div><div className="principles-grid">{copy.principles.map(([title, text], index) => <article key={title}><span>0{index + 1}</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
    <section className="section"><div className="container section-heading"><div><p className="eyebrow">{copy.complete}</p><h2>{copy.all}</h2></div><Link className="text-link" href={route(locale, "/products")}>{copy.search} <span>↗</span></Link></div><div className="container compact-product-grid">{products.map(product => <article key={product.slug}><Link href={route(locale, `/products/${product.slug}`)}><span>{String(product.number).padStart(2, "0")}</span><div><small>{product.code} · {product.localizedCategory}</small><h3>{product.localizedName}</h3></div></Link><LocalizedProductPrice product={product} locale={locale} compact /></article>)}</div><div className="container collection-note"><p>{m.price.estimate}</p><p>{m.price.terms}</p></div></section>
    <section className="quote-banner"><div className="container"><p className="eyebrow">{m.common.collection}</p><h2>{copy.request}</h2><p>{copy.requestText}</p><Link className="button button-dark" href={route(locale, "/products")}>{copy.choose}</Link></div></section>
  </>;
}

const projectCopy = {
  en: { eye: "Custom Projects", title: "From one room to a complete interior.", text: "MULIFANG coordinates custom furniture packages for residential, hospitality, workplace and commercial environments.", categories: "Project Categories", categoriesTitle: "Built for different ways of living and working.", types: ["Residential Homes", "Condominiums & Apartments", "Hotels", "Serviced Apartments", "Corporate Offices", "Restaurants & Cafés", "Retail Stores", "Commercial Projects", "Villa Design Concepts"], approach: "Project Approach", approachTitle: "One accountable process.", approachText: "Design coordination, engineering, production and installation stay connected from the first measurement to final handover.", steps: ["Consultation", "Site Measurement", "Concept Design", "Material Selection", "Quotation", "Engineering Drawings", "CNC Manufacturing", "Quality Inspection", "Delivery", "Installation", "Project Handover"], interior: "Interior Design Capability", interiorTitle: "Furniture, cabinetry and room planning in one system.", interiorText: "From a single storage wall to a coordinated room package, every element is developed around function, proportion, materials and the character of the space.", cards: [["kitchen-project", "Kitchen & Pantry Systems", "Coordinated cabinetry, work zones and finishes planned around everyday use."], ["hallway-project", "Entry & Hallway Cabinetry", "Purpose-built storage keeps arrival spaces calm and functional."], ["wardrobe-project", "Wardrobe & Storage Planning", "Integrated storage tailored to the room and daily routine."]], villa: "Villa Design Capability", villaTitle: "Architecture and interiors, developed as one idea.", villaText: "MULIFANG extends its design thinking beyond individual furniture pieces, coordinating villa exterior concepts with the materials, forms and interior language of the complete home.", concepts: [["Geometric Warm Modern", "Bold framed volumes, warm feature surfaces and patterned screens create a distinctive contemporary frontage."], ["Sculptural Urban Villa", "Curved balconies and a vertical decorative screen combine privacy, natural light and a memorable street presence."], ["Stone & Circular Form", "Natural stone, strong black volumes and a sweeping circular frame connect the villa to its landscape."]], note: "Villa images present design concepts and visual direction. Final architectural, structural, building-services and permitting documents must be reviewed and completed by appropriately licensed professionals where required.", enquiry: "Project Enquiry", enquiryTitle: "Bring us your plans.", enquiryText: "Share drawings, dimensions, reference images or a simple description. We will help define the next step.", start: "Start a Project" },
  zh: { eye: "定制项目", title: "从一个房间到完整室内空间。", text: "MULIFANG 为住宅、酒店、办公与商业环境协同提供定制家具方案。", categories: "项目类别", categoriesTitle: "为不同生活与工作方式而打造。", types: ["住宅", "公寓与共管公寓", "酒店", "服务式公寓", "企业办公室", "餐厅与咖啡馆", "零售店", "商业项目", "别墅设计方案"], approach: "项目方法", approachTitle: "一套全程负责的流程。", approachText: "从首次测量到最终交付，设计协调、工程深化、生产与安装始终保持衔接。", steps: ["需求沟通", "现场测量", "概念设计", "材料选择", "报价", "工程图纸", "CNC 制造", "质量检验", "配送", "安装", "项目交付"], interior: "室内设计能力", interiorTitle: "家具、柜体与空间规划统一协同。", interiorText: "从单面收纳墙到完整房间方案，每个元素均围绕功能、比例、材料与空间特征展开。", cards: [["kitchen-project", "厨房与餐具室系统", "围绕日常使用协调柜体、工作区与饰面。"], ["hallway-project", "玄关与走廊柜体", "定制收纳让入口空间整洁、实用。"], ["wardrobe-project", "衣柜与收纳规划", "根据房间与日常习惯规划一体化收纳。"]], villa: "别墅设计能力", villaTitle: "建筑与室内，源于同一个设计理念。", villaText: "MULIFANG 将设计能力从单件家具延伸至别墅外观概念，使材料、形态与完整家居的室内语言相互协调。", concepts: [["几何暖现代", "大胆框景、温暖特色表面与图案屏风塑造鲜明的当代立面。"], ["雕塑感都市别墅", "曲线阳台与竖向装饰屏风兼顾私密、采光与街道形象。"], ["石材与圆形构图", "天然石材、黑色体块与圆弧框架将建筑融入景观。"]], note: "别墅图片用于呈现设计概念与视觉方向。最终建筑、结构、设备与许可文件须由具备相应资质的专业人士审核完成。", enquiry: "项目咨询", enquiryTitle: "把您的图纸交给我们。", enquiryText: "分享图纸、尺寸、参考图片或简单说明，我们将协助确定下一步。", start: "启动项目" },
  ko: { eye: "맞춤 프로젝트", title: "한 공간부터 전체 인테리어까지.", text: "MULIFANG은 주거, 호스피탈리티, 업무 및 상업 환경을 위한 맞춤 가구 패키지를 조율합니다.", categories: "프로젝트 카테고리", categoriesTitle: "다양한 생활과 업무 방식을 위해 제작합니다.", types: ["주택", "콘도미니엄 및 아파트", "호텔", "서비스드 아파트", "기업 오피스", "레스토랑 및 카페", "리테일 매장", "상업 프로젝트", "빌라 디자인 콘셉트"], approach: "프로젝트 방식", approachTitle: "하나의 책임 있는 프로세스.", approachText: "첫 실측부터 최종 인도까지 디자인 조율, 엔지니어링, 생산 및 설치가 연결됩니다.", steps: ["상담", "현장 실측", "콘셉트 디자인", "소재 선택", "견적", "엔지니어링 도면", "CNC 제조", "품질 검사", "배송", "설치", "프로젝트 인도"], interior: "인테리어 디자인 역량", interiorTitle: "가구, 캐비닛과 공간 계획을 하나의 시스템으로.", interiorText: "하나의 수납 벽부터 통합 공간 패키지까지 기능, 비례, 소재와 공간의 성격에 맞춰 개발합니다.", cards: [["kitchen-project", "주방 및 팬트리 시스템", "일상 사용에 맞춘 캐비닛, 작업 구역과 마감을 통합합니다."], ["hallway-project", "현관 및 복도 캐비닛", "맞춤 수납으로 입구 공간을 정돈하고 실용적으로 만듭니다."], ["wardrobe-project", "옷장 및 수납 계획", "공간과 일상 습관에 맞춘 통합 수납을 계획합니다."]], villa: "빌라 디자인 역량", villaTitle: "건축과 인테리어를 하나의 아이디어로 완성합니다.", villaText: "MULIFANG은 개별 가구를 넘어 빌라 외관 콘셉트와 집 전체의 소재, 형태 및 인테리어 언어를 통합합니다.", concepts: [["지오메트릭 웜 모던", "대담한 프레임, 따뜻한 포인트 표면과 패턴 스크린이 현대적 입면을 만듭니다."], ["조형적 어반 빌라", "곡선형 발코니와 수직 장식 스크린이 프라이버시, 자연광과 거리 풍경을 조화시킵니다."], ["석재와 원형 구성", "천연 석재, 블랙 볼륨과 원형 프레임이 빌라를 풍경과 연결합니다."]], note: "빌라 이미지는 디자인 콘셉트와 시각적 방향을 제시합니다. 최종 건축, 구조, 설비 및 인허가 문서는 필요한 자격을 갖춘 전문가가 검토하고 완성해야 합니다.", enquiry: "프로젝트 문의", enquiryTitle: "도면을 공유해 주세요.", enquiryText: "도면, 치수, 참고 이미지 또는 간단한 설명을 보내 주시면 다음 단계를 안내합니다.", start: "프로젝트 시작" }
} as const;

export function RestoredProjectsPage({ locale }: { locale: Locale }) {
  const copy = projectCopy[locale];
  return <><PageHero eyebrow={copy.eye} title={copy.title} text={copy.text} />
    <section className="content-section"><div className="container"><div className="section-heading"><div><p className="eyebrow">{copy.categories}</p><h2>{copy.categoriesTitle}</h2></div></div><div className="project-types">{copy.types.map((item, index) => <div className="project-type" key={item}><span>{String(index + 1).padStart(2, "0")}</span><h3>{item}</h3></div>)}</div></div></section>
    <section className="content-section alt project-approach"><div className="container"><div className="section-heading"><div><p className="eyebrow">{copy.approach}</p><h2>{copy.approachTitle}</h2></div><p className="lead">{copy.approachText}</p></div><ol className="workflow">{copy.steps.map(step => <li key={step}><strong>{step}</strong></li>)}</ol></div></section>
    <section className="content-section interior-section"><div className="container"><div className="section-heading"><div><p className="eyebrow">{copy.interior}</p><h2>{copy.interiorTitle}</h2></div><p>{copy.interiorText}</p></div><div className="interior-project-grid">{copy.cards.map(([image, title, text]) => <article className="interior-project-card" key={title}><div className="image-wrap"><Image src={`/images/projects/${image}.webp`} alt={title} fill sizes="(max-width:760px) 100vw, 33vw" /></div><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
    <section className="content-section alt villa-section"><div className="container"><div className="section-heading"><div><p className="eyebrow">{copy.villa}</p><h2>{copy.villaTitle}</h2></div><p>{copy.villaText}</p></div><div className="villa-grid">{copy.concepts.map(([title, text], index) => <article className="villa-card" key={title}><div className="image-wrap"><Image src={`/images/projects/villa-concept-0${index + 1}.webp`} alt={title} fill sizes="(max-width:760px) 100vw, 33vw" /></div><p className="eyebrow">{String(index + 1).padStart(2, "0")}</p><h3>{title}</h3><p>{text}</p></article>)}</div><p className="villa-note">{copy.note}</p></div></section>
    <section className="quote-banner"><div className="container"><p className="eyebrow">{copy.enquiry}</p><h2>{copy.enquiryTitle}</h2><p>{copy.enquiryText}</p><Link className="button button-dark" href={`${route(locale, "/contact")}#quotation`}>{copy.start}</Link></div></section>
  </>;
}

const factoryCopy = {
  en: { eye: "Factory Capability", title: "A production workflow built for precision.", text: "Our 4,800 m² facility in Bamban coordinates 12 major production machines, skilled assembly and quality inspection for custom and batch projects.", equipment: [["CNC Cutting", "Computer-guided panel processing supports repeatable, project-specific component production."], ["Edge Banding", "Coordinated edge finishing helps protect panels and deliver clean, consistent lines."], ["Machining & Drilling", "Production equipment supports accurate drilling and machining for assembly and hardware."], ["Dust Collection", "Central dust collection supports a cleaner, more controlled production environment."]], scope: "Production Scope", scopeTitle: "From panel processing to protected delivery.", scopeText: "Our workflow connects manufacturing steps with inspection, packing and project coordination.", capabilities: ["CNC cutting", "Edge banding", "Drilling", "Machining", "Assembly", "Quality inspection", "Dust collection", "Packaging", "Delivery coordination", "Custom production", "Batch production", "Installation coordination"], stats: ["Factory area", "Major machines", "Current employees", "Planned workforce"], enquiry: "Production Enquiry", enquiryTitle: "Discuss your manufacturing needs.", enquiryText: "Send your project scope for a quotation based on materials, dimensions, quantities and installation requirements." },
  zh: { eye: "工厂能力", title: "为精准制造而构建的生产流程。", text: "班班 4,800 平方米工厂整合 12 台主要生产设备、熟练组装与质量检验，为定制与批量项目提供支持。", equipment: [["CNC 开料", "电脑引导的板材加工支持稳定、按项目定制的部件生产。"], ["封边", "协调的封边工艺保护板材并形成整洁一致的线条。"], ["加工与钻孔", "设备支持装配和五金所需的精准钻孔与加工。"], ["除尘系统", "中央除尘系统有助于保持更清洁、更可控的生产环境。"]], scope: "生产范围", scopeTitle: "从板材加工到安全交付。", scopeText: "生产流程连接制造、检验、包装与项目协调。", capabilities: ["CNC 开料", "封边", "钻孔", "机械加工", "组装", "质量检验", "除尘", "包装", "配送协调", "定制生产", "批量生产", "安装协调"], stats: ["工厂面积", "主要设备", "现有员工", "规划员工"], enquiry: "生产咨询", enquiryTitle: "沟通您的制造需求。", enquiryText: "提交项目范围，我们将根据材料、尺寸、数量及安装要求准备报价。" },
  ko: { eye: "공장 역량", title: "정밀함을 위해 설계된 생산 공정.", text: "밤반의 4,800m² 공장은 12대 주요 생산 설비, 숙련된 조립과 품질 검사를 통합해 맞춤 및 대량 프로젝트를 지원합니다.", equipment: [["CNC 절단", "컴퓨터 제어 패널 가공으로 반복 가능하며 프로젝트에 맞춘 부품을 생산합니다."], ["엣지 밴딩", "조율된 엣지 마감으로 패널을 보호하고 깔끔한 선을 구현합니다."], ["가공 및 드릴링", "조립과 하드웨어 설치를 위한 정밀 가공을 지원합니다."], ["집진 시스템", "중앙 집진 설비로 더 깨끗하고 안정적인 생산 환경을 지원합니다."]], scope: "생산 범위", scopeTitle: "패널 가공부터 안전한 배송까지.", scopeText: "제조, 검사, 포장 및 프로젝트 조율이 하나의 공정으로 연결됩니다.", capabilities: ["CNC 절단", "엣지 밴딩", "드릴링", "가공", "조립", "품질 검사", "집진", "포장", "배송 조율", "맞춤 생산", "대량 생산", "설치 조율"], stats: ["공장 면적", "주요 설비", "현재 직원", "계획 인력"], enquiry: "생산 문의", enquiryTitle: "제조 요구사항을 상담하세요.", enquiryText: "소재, 치수, 수량 및 설치 요구에 따른 견적을 위해 프로젝트 범위를 보내 주세요." }
} as const;

export function RestoredFactoryPage({ locale }: { locale: Locale }) {
  const copy = factoryCopy[locale], images = ["cnc-cutting", "edge-banding", "machining", "dust-collection"], stats = [[company.factoryArea, copy.stats[0]], [company.machines, copy.stats[1]], [company.employees, copy.stats[2]], [company.plannedWorkforce, copy.stats[3]]];
  return <><PageHero eyebrow={copy.eye} title={copy.title} text={copy.text} /><section className="content-section"><div className="container factory-gallery">{copy.equipment.map(([title, text], index) => <article className="factory-card" key={title}><div className="image-wrap"><Image src={`/images/factory/${images[index]}.webp`} alt={title} fill sizes="(max-width:760px) 100vw, 50vw" /></div><h3>{title}</h3><p>{text}</p></article>)}</div></section><section className="content-section alt"><div className="container split"><div><p className="eyebrow">{copy.scope}</p><h2>{copy.scopeTitle}</h2><p className="lead" style={{ marginTop: 30 }}>{copy.scopeText}</p></div><ul className="capability-list">{copy.capabilities.map(item => <li key={item}>{item}</li>)}</ul></div></section><section className="stats-band"><div className="container stats-grid">{stats.map(([value, label]) => <div key={label}><strong>{value}</strong><span>{label}</span></div>)}</div></section><section className="quote-banner"><div className="container"><p className="eyebrow">{copy.enquiry}</p><h2>{copy.enquiryTitle}</h2><p>{copy.enquiryText}</p><Link className="button button-dark" href={`${route(locale, "/contact")}#quotation`}>{messages[locale].quote}</Link></div></section></>;
}

const aboutCopy = {
  en: { eye: "About MULIFANG", title: "Designed for living. Built for life.", text: "A premium custom furniture manufacturer connecting design coordination, engineering, CNC manufacturing, delivery and professional installation.", profile: "Company Profile", profileTitle: "Based in Tarlac. Built to serve growing projects.", profileText: ["MULIFANG INC. is a premium custom furniture manufacturer based in Bamban, Tarlac, Philippines.", "The company provides complete furniture solutions for residential, apartment, hotel, office and commercial projects. Services include consultation, design coordination, engineering, CNC manufacturing, delivery and professional installation.", "Established in 2026, MULIFANG is developing a capable local team and an efficient production base for custom and coordinated project work."], brand: "Brand Position", position: "Premium Custom Furniture Manufacturer", brandText: "Architectural furniture solutions shaped around real spaces and delivered through an accountable process.", direction: "Direction", directionTitle: "What guides our work.", cards: [["Mission", "To provide coordinated custom furniture solutions that combine practical design, precise production and dependable project service."], ["Vision", "To become a trusted Philippine furniture manufacturing partner for complete residential, hospitality, office and commercial interiors."], ["Service Promise", "To communicate clearly, manufacture responsibly and support every approved project through delivery and installation."]], core: "Core Values", coreTitle: "How we work.", values: [["Precision", "We coordinate dimensions, details and production stages with care."], ["Accountability", "One connected team guides each approved project through completion."], ["Practical Design", "Furniture should be refined, durable and genuinely useful every day."], ["Material Respect", "Finishes and components are selected in line with the project purpose."], ["Clear Communication", "Clients receive a defined process from consultation to installation."], ["Long-Term Thinking", "We build relationships and furniture solutions intended to last."]], areas: "Service Areas", areaText: "Consultation, measurement, delivery and installation are scheduled according to project scope and location.", work: "Work With MULIFANG", workTitle: "Plan your next interior with us.", workText: "Tell us about your property, product needs and preferred schedule.", contact: "Contact Our Team" },
  zh: { eye: "关于 MULIFANG", title: "为生活而设计。为品质而打造。", text: "连接设计协调、工程深化、CNC 制造、交付与专业安装的高端定制家具制造商。", profile: "公司简介", profileTitle: "立足丹辘，服务不断成长的项目。", profileText: ["MULIFANG INC. 是一家位于菲律宾丹辘省班班的高端定制家具制造商。", "公司为住宅、公寓、酒店、办公及商业项目提供完整家具解决方案，涵盖咨询、设计协调、工程深化、CNC 制造、交付与专业安装。", "MULIFANG 成立于 2026 年，正在建设专业的本地团队与高效生产基地。"], brand: "品牌定位", position: "高端定制家具制造商", brandText: "围绕真实空间打造建筑化家具解决方案，并通过全程负责的流程交付。", direction: "发展方向", directionTitle: "我们的工作准则。", cards: [["使命", "以实用设计、精准生产与可靠服务提供协同的定制家具解决方案。"], ["愿景", "成为菲律宾住宅与商业完整室内项目值得信赖的家具制造伙伴。"], ["服务承诺", "清晰沟通、负责制造，并为获批项目提供从交付到安装的支持。"]], core: "核心价值", coreTitle: "我们的工作方式。", values: [["精准", "认真协调尺寸、细节与生产阶段。"], ["责任", "由一个协同团队推动获批项目直至完成。"], ["实用设计", "家具应精致、耐用，并真正服务日常生活。"], ["尊重材料", "依据项目用途选择饰面与部件。"], ["清晰沟通", "从咨询到安装保持明确流程。"], ["长期思维", "建立可持续的合作关系与家具解决方案。"]], areas: "服务区域", areaText: "咨询、测量、配送与安装将根据项目范围和地点安排。", work: "与 MULIFANG 合作", workTitle: "与我们规划您的下一个室内项目。", workText: "请告诉我们物业情况、产品需求与期望时间。", contact: "联系团队" },
  ko: { eye: "MULIFANG 소개", title: "삶을 위한 디자인. 오래도록 함께하는 품질.", text: "디자인 조율, 엔지니어링, CNC 제조, 배송 및 전문 설치를 연결하는 프리미엄 맞춤 가구 제조업체입니다.", profile: "회사 프로필", profileTitle: "딸락을 기반으로 성장하는 프로젝트를 지원합니다.", profileText: ["MULIFANG INC.는 필리핀 딸락주 밤반에 위치한 프리미엄 맞춤 가구 제조업체입니다.", "주택, 아파트, 호텔, 오피스 및 상업 프로젝트를 위해 상담, 디자인 조율, 엔지니어링, CNC 제조, 배송 및 전문 설치를 제공합니다.", "2026년에 설립된 MULIFANG은 맞춤 프로젝트를 위한 전문 현지 팀과 효율적인 생산 기반을 구축하고 있습니다."], brand: "브랜드 포지션", position: "프리미엄 맞춤 가구 제조업체", brandText: "실제 공간에 맞춘 건축적 가구 솔루션을 하나의 책임 있는 과정으로 제공합니다.", direction: "방향", directionTitle: "우리의 업무 원칙.", cards: [["미션", "실용적 디자인, 정밀한 생산과 신뢰할 수 있는 서비스로 통합 맞춤 가구 솔루션을 제공합니다."], ["비전", "필리핀의 주거 및 상업 인테리어를 위한 신뢰받는 가구 제조 파트너가 됩니다."], ["서비스 약속", "명확히 소통하고 책임 있게 제조하며 승인된 프로젝트의 배송과 설치까지 지원합니다."]], core: "핵심 가치", coreTitle: "우리의 업무 방식.", values: [["정밀함", "치수, 디테일 및 생산 단계를 세심하게 조율합니다."], ["책임감", "하나의 협업 팀이 승인된 프로젝트를 완료까지 안내합니다."], ["실용적 디자인", "세련되고 내구성이 뛰어나며 일상에 유용한 가구를 만듭니다."], ["소재 존중", "프로젝트 목적에 맞는 마감과 부품을 선택합니다."], ["명확한 소통", "상담부터 설치까지 명확한 절차를 제공합니다."], ["장기적 관점", "오래 지속되는 관계와 가구 솔루션을 구축합니다."]], areas: "서비스 지역", areaText: "상담, 실측, 배송 및 설치는 프로젝트 범위와 위치에 따라 일정이 조율됩니다.", work: "MULIFANG과 함께", workTitle: "다음 인테리어 프로젝트를 계획하세요.", workText: "공간, 제품 요구사항과 희망 일정을 알려주세요.", contact: "팀에 문의" }
} as const;

export function RestoredAboutPage({ locale }: { locale: Locale }) {
  const copy = aboutCopy[locale], areas = pick(locale, { en: company.areas.join(" · "), zh: "马尼拉大都会 · 邦板牙 · 丹辘", ko: "메트로 마닐라 · 팜팡가 · 딸락" });
  return <><PageHero eyebrow={copy.eye} title={copy.title} text={copy.text} /><section className="content-section"><div className="container split"><div><p className="eyebrow">{copy.profile}</p><h2>{copy.profileTitle}</h2></div><div className="intro-copy">{copy.profileText.map(text => <p key={text}>{text}</p>)}</div></div></section><section className="content-section alt"><div className="container factory-layout"><div><p className="eyebrow">{copy.brand}</p><h2>{copy.position}</h2><p className="lead" style={{ marginTop: 28 }}>{copy.brandText}</p></div><div className="image-wrap" style={{ aspectRatio: "16/10" }}><Image src="/images/projects/living-project.webp" alt={copy.position} fill sizes="60vw" /></div></div></section><section className="content-section"><div className="container"><div className="section-heading"><div><p className="eyebrow">{copy.direction}</p><h2>{copy.directionTitle}</h2></div></div><div className="values-grid">{copy.cards.map(([title, text]) => <div className="value-card" key={title}><h3>{title}</h3><p>{text}</p></div>)}</div></div></section><section className="content-section alt"><div className="container"><div className="section-heading"><div><p className="eyebrow">{copy.core}</p><h2>{copy.coreTitle}</h2></div></div><div className="values-grid">{copy.values.map(([title, text]) => <div className="value-card" key={title}><h3>{title}</h3><p>{text}</p></div>)}</div></div></section><section className="service-area"><div className="container"><p className="eyebrow light">{copy.areas}</p><h2>{areas}</h2><p>{copy.areaText}</p></div></section><section className="quote-banner"><div className="container"><p className="eyebrow">{copy.work}</p><h2>{copy.workTitle}</h2><p>{copy.workText}</p><Link className="button button-dark" href={`${route(locale, "/contact")}#quotation`}>{copy.contact}</Link></div></section></>;
}
