import type { Locale } from "./config";

const en = {
  nav: ["Home", "Products", "Collection 2026", "Custom Projects", "Factory", "About", "Contact"],
  quote: "Request a Quote", freeQuote: "Request a Free Quote", menu: "Open menu", language: "Language", skip: "Skip to content",
  position: "Premium Custom Furniture Manufacturer", slogan: "Designed for Living. Built for Life.",
  footer: { contact: "Contact", visit: "Visit", explore: "Explore", serving: "Serving", maps: "Open in Google Maps", privacy: "Privacy Policy", terms: "Terms of Use", whatsapp: "Contact MULIFANG on WhatsApp" },
  common: { view: "View Details", all: "All", products: "products", product: "product", whatsapp: "WhatsApp", details: "Main Features", materials: "Materials", customization: "Customization", applications: "Suitable Applications", related: "Related Products", continue: "Continue exploring.", allProducts: "All products", code: "Product Code", category: "Category", dimensions: "Dimensions", packaging: "Packaging", status: "Status", active: "Launch collection · Active", customers: "Primary Customers", positioning: "Sales Positioning", gallery: "Product Gallery", additional: "Additional product view.", galleryNote: "Reference imagery supports product selection; final materials and finishes are confirmed in the written quotation.", construction: "Construction Reference", exploded: "Exploded view.", explodedNote: "The component view communicates the launch product’s repeatable board, hardware and assembly logic.", writtenQuote: "Request a Written Quotation", askAbout: "Ask about", requestHelp: "Your request includes the product name, code, reference price and quantity for a faster response.", customSolutions: "Custom Furniture Solutions", collection: "Furniture Collection 2026" },
  price: { estimate: "Market-positioning estimate as of July 2026.", terms: "Final price is subject to confirmed materials, quantity, VAT treatment, freight, installation, warranty and written quotation.", reference: "Reference price only. Final price is subject to written quotation.", upon: "Price available upon written quotation" },
  home: {
    eyebrow: "MULIFANG INC. · Bamban, Tarlac", title: "Premium Custom\nFurniture Manufacturer", heroIndex: ["Custom Furniture", "Doors & Windows", "Project Installation"], viewCollection: "View Product Collection",
    introEye: "Company Introduction", introTitle: "Built around your space,\nnot a catalogue.", intro1: "MULIFANG INC. is a premium custom furniture manufacturer based in Bamban, Tarlac. We deliver complete furniture solutions for homes, apartments, hotels, offices and commercial projects.", intro2: "From consultation and engineering to CNC manufacturing, delivery and professional installation, one coordinated team carries your project from idea to completion.", discover: "Discover MULIFANG",
    stats: ["Factory area", "Major machines", "Current team", "Planned workforce"], collectionTitle: "Five launch heroes.\nBuilt for real living.", exploreCollection: "Explore the launch collection", customEye: "Custom Solutions", customTitle: "One partner.\nEvery room.", customText: "Coordinated furniture, cabinetry, doors, panels and selected window systems for complete interiors.", plan: "Plan a Custom Project", services: ["Residential Homes", "Condominiums & Apartments", "Hotels & Serviced Apartments", "Corporate Offices", "Restaurants & Retail", "Commercial Projects"], factoryEye: "Factory Capability", factoryTitle: "Precision in every stage.", factoryText: "Our 4,800 m² Bamban facility brings CNC cutting, edge banding, drilling, machining, assembly, inspection and packaging into one coordinated workflow.", inside: "Inside the factory", processEye: "Design to Installation", processTitle: "A clear path to completion.", processText: "Transparent project stages keep design decisions, production and installation aligned.", process: ["Consultation", "Site Measurement", "Concept Design", "Material Selection", "Engineering", "CNC Manufacturing", "Quality Inspection", "Installation"], areasEye: "Service Areas", areasText: "Project consultation, measurement, delivery and installation coordinated from our Bamban factory.", startEye: "Start Your Project", startTitle: "Tell us what you want to build.", startText: "Share your space, dimensions and preferred finish. Our team will prepare a quotation based on your project."
  },
  productsPage: { eyebrow: "Two Product Systems · 47 Products", title: "Ready-to-launch furniture. Made-to-order solutions.", text: "Explore the 20-product Furniture Collection 2026 or browse 27 Custom Furniture Solutions engineered around your space and project requirements.", systems: ["All Products", "Furniture Collection 2026", "Custom Furniture Solutions"], search: "Search product name, code or category", filter: "Filter by category", featured: "Featured Launch Product", launchPrefix: "Collection 2026", customPrefix: "Custom Solutions", noMatch: "No matching products", tryAgain: "Try another product name or code, or select All categories." },
  contact: { eyebrow: "Contact MULIFANG", title: "Let’s discuss your space.", text: "Contact our team or prepare a structured quotation request for launch furniture, custom cabinetry, doors, windows, mattresses or a complete project.", direct: "Direct Contact", visit: "Visit, call or message us.", phone: "Phone / WhatsApp", email: "Email", address: "Factory Address", hours: "Business Hours", areas: "Service Areas", map: "MULIFANG factory location" },
  quoteForm: { eyebrow: "Online Quotation", title: "Tell us about your project.", intro: "Required fields are marked *. Product links automatically include the product, code, reference price and quantity.", generate: "Generate Summary", sendWhatsApp: "Send by WhatsApp", sendEmail: "Send by Email", copy: "Copy Summary", required: "Please complete all required fields before preparing or sending the quotation request.", ready: "Your quotation summary is ready. Choose WhatsApp, email or copy below.", sendReady: "Your quotation summary is ready to send.", copied: "Quotation summary copied successfully.", summary: "Generated quotation summary", requestTitle: "MULIFANG QUOTATION REQUEST", unspecified: "Not specified", submitted: "Submitted from the MULIFANG website." },
};

const zh: typeof en = {
  ...en,
  nav: ["首页", "产品", "2026 系列", "定制项目", "工厂", "关于我们", "联系我们"], quote: "申请报价", freeQuote: "申请免费报价", menu: "打开菜单", language: "语言", skip: "跳至主要内容",
  position: "高端定制家具制造商", slogan: "为生活而设计。为品质而打造。",
  footer: { contact: "联系", visit: "到访", explore: "浏览", serving: "服务区域", maps: "在 Google 地图中打开", privacy: "隐私政策", terms: "使用条款", whatsapp: "通过 WhatsApp 联系 MULIFANG" },
  common: { view: "查看详情", all: "全部", products: "款产品", product: "款产品", whatsapp: "WhatsApp", details: "主要特点", materials: "材料", customization: "可定制项目", applications: "适用场景", related: "相关产品", continue: "继续探索。", allProducts: "全部产品", code: "产品代码", category: "类别", dimensions: "尺寸", packaging: "包装", status: "状态", active: "首发系列 · 在售", customers: "主要客户", positioning: "销售定位", gallery: "产品图库", additional: "更多产品视图。", galleryNote: "参考图片用于辅助选品；最终材料与饰面以书面报价确认为准。", construction: "结构参考", exploded: "爆炸结构图。", explodedNote: "部件视图展示首发产品可重复生产的板件、五金与装配逻辑。", writtenQuote: "申请书面报价", askAbout: "咨询", requestHelp: "询价将自动包含产品名称、代码、参考价格与数量，便于我们更快回复。", customSolutions: "定制家具解决方案", collection: "MULIFANG 2026 家具系列" },
  price: { estimate: "截至 2026 年 7 月的市场定位参考价。", terms: "最终价格以确认的材料、数量、增值税处理、运输、安装、保修及书面报价为准。", reference: "仅供参考。最终价格以书面报价为准。", upon: "价格以书面报价为准" },
  home: { ...en.home, eyebrow: "MULIFANG INC. · 菲律宾丹辘省班班", title: "高端定制家具制造商", heroIndex: ["定制家具", "门窗系统", "项目安装"], viewCollection: "查看产品系列", introEye: "公司简介", introTitle: "围绕您的空间打造，\n而非照搬目录。", intro1: "MULIFANG INC. 是一家位于菲律宾丹辘省班班的高端定制家具制造商，为住宅、公寓、酒店、办公室及商业项目提供完整家具解决方案。", intro2: "从咨询、深化设计到 CNC 制造、交付和专业安装，由同一支协同团队将项目从构想推进至落地。", discover: "了解 MULIFANG", stats: ["工厂面积", "主要设备", "现有团队", "规划团队"], collectionTitle: "五款主推新品，\n为真实生活而造。", exploreCollection: "探索 2026 首发系列", customEye: "定制解决方案", customTitle: "一个合作伙伴，\n覆盖每个空间。", customText: "为完整室内空间协同提供家具、柜体、门、饰面板及精选窗系统。", plan: "规划定制项目", services: ["住宅", "公寓与共管公寓", "酒店与服务式公寓", "企业办公室", "餐饮与零售", "商业项目"], factoryEye: "工厂能力", factoryTitle: "每个环节，精准把控。", factoryText: "4,800 平方米班班工厂将 CNC 开料、封边、钻孔、加工、组装、检验与包装整合为一套协同流程。", inside: "走进工厂", processEye: "从设计到安装", processTitle: "清晰的项目交付路径。", processText: "透明的项目阶段让设计决策、生产与安装始终保持一致。", process: ["需求沟通", "现场测量", "概念设计", "材料选择", "工程深化", "CNC 制造", "质量检验", "安装"], areasEye: "服务区域", areasText: "项目咨询、测量、配送与安装由班班工厂统一协调。", startEye: "启动您的项目", startTitle: "告诉我们您想打造什么。", startText: "分享空间、尺寸与理想饰面，我们将根据项目准备报价。" },
  productsPage: { eyebrow: "两大产品体系 · 47 款产品", title: "标准化新品与量身定制解决方案。", text: "浏览 20 款 MULIFANG 2026 家具系列产品，或探索围绕空间与项目需求设计的 27 类定制家具解决方案。", systems: ["全部产品", "2026 家具系列", "定制家具解决方案"], search: "搜索产品名称、代码或类别", filter: "按类别筛选", featured: "首发主推产品", launchPrefix: "2026 系列", customPrefix: "定制方案", noMatch: "没有匹配产品", tryAgain: "请尝试其他产品名称或代码，或选择全部类别。" },
  contact: { eyebrow: "联系 MULIFANG", title: "让我们聊聊您的空间。", text: "联系团队，或为首发家具、定制柜体、门窗、床垫及完整项目提交结构化询价。", direct: "直接联系", visit: "欢迎到访、致电或留言。", phone: "电话 / WhatsApp", email: "电子邮箱", address: "工厂地址", hours: "营业时间", areas: "服务区域", map: "MULIFANG 工厂位置" },
  quoteForm: { eyebrow: "在线询价", title: "请介绍您的项目。", intro: "带 * 的项目为必填。通过产品页进入时，将自动带入产品名称、代码、参考价格和数量。", generate: "生成询价摘要", sendWhatsApp: "通过 WhatsApp 发送", sendEmail: "通过邮件发送", copy: "复制摘要", required: "请先填写所有必填字段，再生成或发送询价。", ready: "询价摘要已生成，可选择 WhatsApp、邮件或复制。", sendReady: "询价摘要已准备发送。", copied: "询价摘要已复制。", summary: "已生成的询价摘要", requestTitle: "MULIFANG 询价申请", unspecified: "未填写", submitted: "通过 MULIFANG 网站提交。" }
};

const ko: typeof en = {
  ...en,
  nav: ["홈", "제품", "2026 컬렉션", "맞춤 프로젝트", "공장", "회사 소개", "문의"], quote: "견적 요청", freeQuote: "무료 견적 요청", menu: "메뉴 열기", language: "언어", skip: "본문으로 이동",
  position: "프리미엄 맞춤 가구 제조업체", slogan: "삶을 위한 디자인. 오래도록 함께하는 품질.",
  footer: { contact: "연락처", visit: "방문", explore: "둘러보기", serving: "서비스 지역", maps: "Google 지도에서 보기", privacy: "개인정보 처리방침", terms: "이용약관", whatsapp: "WhatsApp으로 MULIFANG에 문의" },
  common: { view: "상세 보기", all: "전체", products: "개 제품", product: "개 제품", whatsapp: "WhatsApp", details: "주요 특징", materials: "소재", customization: "맞춤 옵션", applications: "권장 적용 공간", related: "관련 제품", continue: "계속 둘러보기.", allProducts: "모든 제품", code: "제품 코드", category: "카테고리", dimensions: "크기", packaging: "포장", status: "상태", active: "출시 컬렉션 · 판매 중", customers: "주요 고객", positioning: "판매 포지셔닝", gallery: "제품 갤러리", additional: "추가 제품 이미지.", galleryNote: "참고 이미지는 제품 선택을 돕기 위한 것이며, 최종 소재와 마감은 서면 견적에서 확정됩니다.", construction: "구조 참고", exploded: "분해도.", explodedNote: "분해도는 출시 제품의 반복 생산 가능한 보드, 하드웨어 및 조립 구조를 보여줍니다.", writtenQuote: "서면 견적 요청", askAbout: "문의 제품", requestHelp: "빠른 상담을 위해 제품명, 코드, 참고 가격 및 수량이 요청서에 자동 포함됩니다.", customSolutions: "맞춤 가구 솔루션", collection: "MULIFANG 가구 컬렉션 2026" },
  price: { estimate: "2026년 7월 기준 시장 포지셔닝 참고 가격입니다.", terms: "최종 가격은 확정 소재, 수량, VAT 적용, 운송, 설치, 보증 및 서면 견적에 따라 달라집니다.", reference: "참고 가격입니다. 최종 가격은 서면 견적에 따릅니다.", upon: "가격은 서면 견적 후 확정됩니다" },
  home: { ...en.home, eyebrow: "MULIFANG INC. · 밤반, 딸락", title: "프리미엄 맞춤 가구 제조업체", heroIndex: ["맞춤 가구", "도어 & 윈도우", "프로젝트 설치"], viewCollection: "제품 컬렉션 보기", introEye: "회사 소개", introTitle: "카탈로그가 아닌,\n당신의 공간에 맞춰 만듭니다.", intro1: "MULIFANG INC.는 필리핀 딸락주 밤반에 위치한 프리미엄 맞춤 가구 제조업체입니다. 주택, 아파트, 호텔, 사무실 및 상업 프로젝트를 위한 종합 가구 솔루션을 제공합니다.", intro2: "상담과 엔지니어링부터 CNC 제조, 배송 및 전문 설치까지 하나의 협업 팀이 아이디어를 완성된 공간으로 구현합니다.", discover: "MULIFANG 알아보기", stats: ["공장 면적", "주요 설비", "현재 인력", "계획 인력"], collectionTitle: "다섯 가지 대표 신제품.\n실제 생활을 위해 설계했습니다.", exploreCollection: "출시 컬렉션 보기", customEye: "맞춤 솔루션", customTitle: "하나의 파트너로,\n모든 공간을 완성합니다.", customText: "완성도 높은 인테리어를 위한 가구, 캐비닛, 도어, 패널 및 엄선된 창호 시스템을 통합 제공합니다.", plan: "맞춤 프로젝트 상담", services: ["주거 공간", "콘도미니엄 & 아파트", "호텔 & 서비스드 아파트", "기업 사무실", "레스토랑 & 리테일", "상업 프로젝트"], factoryEye: "공장 역량", factoryTitle: "모든 공정의 정밀함.", factoryText: "4,800m² 규모의 밤반 공장은 CNC 절단, 엣지 밴딩, 드릴링, 가공, 조립, 검사 및 포장을 하나의 통합 공정으로 운영합니다.", inside: "공장 둘러보기", processEye: "디자인부터 설치까지", processTitle: "완성까지 이어지는 명확한 과정.", processText: "투명한 프로젝트 단계로 디자인 의사결정, 생산 및 설치를 일관되게 조율합니다.", process: ["상담", "현장 실측", "콘셉트 디자인", "소재 선택", "엔지니어링", "CNC 제조", "품질 검사", "설치"], areasEye: "서비스 지역", areasText: "프로젝트 상담, 실측, 배송 및 설치를 밤반 공장에서 통합 조율합니다.", startEye: "프로젝트 시작", startTitle: "만들고 싶은 공간을 알려주세요.", startText: "공간, 치수, 선호 마감을 공유해 주시면 프로젝트에 맞는 견적을 준비해 드립니다." },
  productsPage: { eyebrow: "두 가지 제품 시스템 · 47개 제품", title: "출시 준비 가구와 주문 제작 솔루션.", text: "20개 MULIFANG 가구 컬렉션 2026 제품과 공간 및 프로젝트 요구에 맞춘 27개 맞춤 가구 솔루션을 만나보세요.", systems: ["모든 제품", "가구 컬렉션 2026", "맞춤 가구 솔루션"], search: "제품명, 코드 또는 카테고리 검색", filter: "카테고리로 필터", featured: "대표 출시 제품", launchPrefix: "2026 컬렉션", customPrefix: "맞춤 솔루션", noMatch: "일치하는 제품이 없습니다", tryAgain: "다른 제품명이나 코드를 입력하거나 전체 카테고리를 선택하세요." },
  contact: { eyebrow: "MULIFANG 문의", title: "당신의 공간에 대해 이야기해 주세요.", text: "출시 가구, 맞춤 캐비닛, 도어, 창호, 매트리스 또는 전체 프로젝트에 대해 문의하거나 체계적인 견적 요청을 준비하세요.", direct: "직접 문의", visit: "방문, 전화 또는 메시지로 문의하세요.", phone: "전화 / WhatsApp", email: "이메일", address: "공장 주소", hours: "영업시간", areas: "서비스 지역", map: "MULIFANG 공장 위치" },
  quoteForm: { eyebrow: "온라인 견적", title: "프로젝트를 알려주세요.", intro: "* 표시는 필수 항목입니다. 제품 링크를 통해 접속하면 제품명, 코드, 참고 가격 및 수량이 자동 입력됩니다.", generate: "요약 생성", sendWhatsApp: "WhatsApp으로 보내기", sendEmail: "이메일로 보내기", copy: "요약 복사", required: "견적 요청을 준비하거나 보내기 전에 모든 필수 항목을 입력해 주세요.", ready: "견적 요약이 준비되었습니다. WhatsApp, 이메일 또는 복사를 선택하세요.", sendReady: "견적 요약을 보낼 준비가 되었습니다.", copied: "견적 요약을 복사했습니다.", summary: "생성된 견적 요약", requestTitle: "MULIFANG 견적 요청", unspecified: "미입력", submitted: "MULIFANG 웹사이트에서 제출되었습니다." }
};

export const messages: Record<Locale, typeof en> = { en, zh, ko };
export type Messages = typeof en;
