import Image from "next/image";
import Link from "next/link";
import { PageHero } from "@/components/PageHero";
import { createPageMetadata } from "@/data/site";

export const metadata = createPageMetadata({ title: "Custom Furniture & Villa Design Projects", description: "Custom furniture, complete interior and select villa design concepts for homes, apartments, hotels, offices, restaurants and retail in the Philippines.", path: "/custom-projects" });
const types = ["Residential Homes", "Condominiums & Apartments", "Hotels", "Serviced Apartments", "Corporate Offices", "Restaurants & Cafés", "Retail Stores", "Commercial Projects", "Villa Design Concepts"];
const interiorConcepts = [
  { image: "/images/projects/kitchen-project.webp", title: "Kitchen & Pantry Systems", text: "Coordinated cabinetry, work zones and finishes planned around everyday use." },
  { image: "/images/projects/hallway-project.webp", title: "Entry & Hallway Cabinetry", text: "Purpose-built storage that keeps arrival spaces calm, functional and welcoming." },
  { image: "/images/projects/wardrobe-project.webp", title: "Wardrobe & Storage Planning", text: "Integrated storage layouts tailored to the room, collection and daily routine." },
];
const villaConcepts = [
  { image: "/images/projects/villa-concept-01.webp", number: "01", title: "Geometric Warm Modern", text: "Bold framed volumes, warm feature surfaces and patterned screens create a distinctive contemporary frontage." },
  { image: "/images/projects/villa-concept-02.webp", number: "02", title: "Sculptural Urban Villa", text: "Curved balconies and a vertical decorative screen combine privacy, natural light and a memorable street presence." },
  { image: "/images/projects/villa-concept-03.webp", number: "03", title: "Stone & Circular Form", text: "Natural stone, strong black volumes and a sweeping circular frame connect the villa to its landscape." },
];
const workflow = [
  ["Consultation", "Define the spaces, priorities, style direction and target schedule."], ["Site Measurement", "Record site conditions and the dimensions required for planning."], ["Concept Design", "Coordinate layouts, visual direction and functional requirements."], ["Material Selection", "Select suitable panels, finishes, hardware and related components."], ["Quotation", "Prepare a project-specific scope and quotation for approval."], ["Engineering Drawings", "Translate approved concepts into production-ready details."], ["CNC Manufacturing", "Produce components through the coordinated factory workflow."], ["Quality Inspection", "Inspect workmanship, dimensions, finishes and completeness."], ["Delivery", "Schedule protected transport and site coordination."], ["Installation", "Assemble, align and complete the approved furniture at site."], ["Project Handover", "Review the completed scope with the client and hand over the project."],
];

export default function ProjectsPage() { return <>
  <PageHero eyebrow="Custom Projects" title="From one room to a complete interior." text="MULIFANG coordinates custom furniture packages for residential, hospitality, workplace and commercial environments." />
  <section className="content-section"><div className="container"><div className="section-heading"><div><p className="eyebrow">Project Categories</p><h2>Built for different ways of living and working.</h2></div></div><div className="project-types">{types.map((item, i) => <div className="project-type" key={item}><span>{String(i + 1).padStart(2, "0")}</span><h3>{item}</h3></div>)}</div></div></section>
  <section className="content-section alt project-approach"><div className="container"><div className="section-heading"><div><p className="eyebrow">Project Approach</p><h2>One accountable process.</h2></div><p className="lead">Design coordination, engineering, production and installation stay connected from the first measurement to final handover.</p></div><ol className="workflow">{workflow.map(([title, text]) => <li key={title}><strong>{title}</strong><p>{text}</p></li>)}</ol></div></section>
  <section className="content-section interior-section"><div className="container"><div className="section-heading"><div><p className="eyebrow">Interior Design Capability</p><h2>Furniture, cabinetry and room planning in one system.</h2></div><p>From a single storage wall to a coordinated room package, every element is developed around function, proportion, materials and the character of the space.</p></div><div className="interior-project-grid">{interiorConcepts.map((concept) => <article className="interior-project-card" key={concept.title}><div className="image-wrap"><Image src={concept.image} alt={`${concept.title} design concept`} fill sizes="(max-width:760px) 100vw, 33vw" /></div><h3>{concept.title}</h3><p>{concept.text}</p></article>)}</div></div></section>
  <section className="content-section alt villa-section"><div className="container"><div className="section-heading"><div><p className="eyebrow">Villa Design Capability</p><h2>Architecture and interiors,<br />developed as one idea.</h2></div><p>MULIFANG extends its design thinking beyond individual furniture pieces, coordinating villa exterior concepts with the materials, forms and interior language of the complete home.</p></div><div className="villa-grid">{villaConcepts.map((concept) => <article className="villa-card" key={concept.number}><div className="image-wrap"><Image src={concept.image} alt={`${concept.title} villa exterior design concept`} fill sizes="(max-width:760px) 100vw, 33vw" /></div><p className="eyebrow">Concept {concept.number}</p><h3>{concept.title}</h3><p>{concept.text}</p></article>)}</div><p className="villa-note">Villa images present design concepts and visual direction. Final architectural, structural, building-services and permitting documents must be reviewed and completed by appropriately licensed professionals where required.</p></div></section>
  <section className="quote-banner"><div className="container"><p className="eyebrow">Project Enquiry</p><h2>Bring us your plans.</h2><p>Share drawings, dimensions, reference images or a simple description. We will help define the next step.</p><Link className="button button-dark" href="/contact#quotation">Start a Project</Link></div></section>
  </>; }
